apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true
    net:
      port: 27017
      bindIp: 0.0.0.0
    security:
      authorization: enabled

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      initContainers:
      - name: init-chmod-data
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /var/log/mongodb && mkdir -p /usr/share/filebeat/data && chmod -R 777 /usr/share/filebeat/data"]
        volumeMounts:
        - name: mongodb-logs
          mountPath: /var/log/mongodb
        - name: filebeat-data
          mountPath: /usr/share/filebeat/data
      containers:
      - name: mongodb
        image: mongo:latest
        command:
        - mongod
        - --config
        - /etc/mongo/mongod.conf
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: mongodb-logs
          mountPath: /var/log/mongodb
        - name: mongo-config
          mountPath: /etc/mongo
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.13.4
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: mongodb-logs
          mountPath: /var/log/mongodb
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: filebeat-data
          mountPath: /usr/share/filebeat/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: mongo-pvc
      - name: mongodb-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: filebeat-config
      - name: mongo-config
        configMap:
          name: mongo-config
      - name: filebeat-data
        emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/mongodb/*.log
    output.logstash:
      hosts: ["logstash-service:5044"]
    logging.level: debug
