apiVersion: v1
kind: Service
metadata:
  name: movies-serv
spec:
  selector:
    app: movies-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-service
  template:
    metadata:
      labels:
        app: movies-service
    spec:
      containers:
        - name: movies-service
          image: movies-service:v1.0.16
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: DB_SERVERS
              value: "mongo:27017/movies"
            - name: DB_USER
              value: "admin"
            - name: DB_PASS
              value: "password"
            - name: PORT
              value: "3001"
