apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - name: catalog-service
        image: catalog-service:v1.0.1
        ports:
        - containerPort: 3000
        env:
        - name: DB_SERVERS
          value: "mongodb-service:27017"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        - name: PORT
          value: "3000"
        - name: NGINX_SERVICE
          value: "http://nginx-service"
        - name: LOG_APPLICATION
          value: "catalog-service"
