apiVersion: v1
kind: Secret
metadata:
  name: stripe-secrets
type: Opaque
data:
  stripe_secret: c2tfdGVzdF81MVBNVDJBUDVBa3d5aUdGYUoyZEFaVXIyc0J1czhOMktyTmpZd2dHdDRocm5ZV1doMXZrcjBmUXRVQ0VQWEVNNjhubE1QZFFMVXJnQTFQWk9UdDBKYWpXbTAwVWRaM0F1Vzc=
  stripe_public: cGtfdGVzdF81MVBNVDJBUDVBa3d5aUdGYW01cXFtTnRkSGFyVXN1ZTlYNlcxS2h6eldLTUU5NFVwSjV3MU5DcklNaHpUNWg2OTBpQWQ5c3YwNk1TZlFIdGl6UDVVSmhjNjAwOE9QU2xZZ3E=
