apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    cluster.name: docker-cluster
    network.host: 0.0.0.0
    xpack.license.self_generated.type: trial
    xpack.security.enabled: true
