apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json_lines
      }
    }

    filter {
      if [application] == "movies-service" {
        drop { }
      }

      if [application] == "catalog-service" {
        drop { }
      }

      if [values][cvc] {
        fingerprint {
          source => ["[values][cvc]"]
          target => "[values][cvc_hashed]"
          method => "SHA256"
          key => "MYYIrufqBc6i7vibMSCBWkxvkQ0+qdc6zCeSgvCu9eo="
          concatenate_sources => false
          base64encode => true
        }
        mutate {
          remove_field => ["[values][cvc]"]
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        user => "elastic"
        password => "changeme"
        index => "cinema-microservice-logs-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
  logstash.yml: |
    http.host: 0.0.0.0
    node.name: logstash
